name: Publish to PyPI

on:
  push:
    tags:
      - "v0.1.0"   # e.g. v0.1.0
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
          name: pypi
          url: https://pypi.org/project/surprise-lstm
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build sdist and wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build  # creates dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

